services:
  service:
    container_name: bond-search-tool-service
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy

  database:
    container_name: bond-search-tool-db
    image: mysql
    env_file: .env
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 5s