source ./.env

export SPRING_DATASOURCE_USERNAME=$MYSQL_USER
export SPRING_DATASOURCE_PASSWORD=$MYSQL_PASSWORD
export SPRING_DATASOURCE_URL=jdbc:mysql://localhost:$MYSQL_PORT/$MYSQL_DATABASE

./gradlew bootRun
